/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = VisWiz.SDK.Client.SwaggerDateConverter;

namespace VisWiz.SDK.Model
{
    /// <summary>
    /// The prices in different currencies for the plan
    /// </summary>
    [DataContract]
    public partial class PlanPrice :  IEquatable<PlanPrice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanPrice" /> class.
        /// </summary>
        /// <param name="uSD">uSD.</param>
        public PlanPrice(int? uSD = default(int?))
        {
            this.USD = uSD;
        }
        
        /// <summary>
        /// Gets or Sets USD
        /// </summary>
        [DataMember(Name="USD", EmitDefaultValue=false)]
        public int? USD { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlanPrice {\n");
            sb.Append("  USD: ").Append(USD).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlanPrice);
        }

        /// <summary>
        /// Returns true if PlanPrice instances are equal
        /// </summary>
        /// <param name="input">Instance of PlanPrice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlanPrice input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.USD == input.USD ||
                    (this.USD != null &&
                    this.USD.Equals(input.USD))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.USD != null)
                    hashCode = hashCode * 59 + this.USD.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
