/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Body2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body2Tests
    {
        // TODO uncomment below to declare an instance variable for Body2
        //private Body2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body2
            //instance = new Body2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body2
        /// </summary>
        [Test]
        public void Body2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body2
            //Assert.IsInstanceOfType<Body2> (instance, "variable 'instance' is a Body2");
        }


        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Test]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

    }

}
