/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing BuildResultsImages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildResultsImagesTests
    {
        // TODO uncomment below to declare an instance variable for BuildResultsImages
        //private BuildResultsImages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuildResultsImages
            //instance = new BuildResultsImages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuildResultsImages
        /// </summary>
        [Test]
        public void BuildResultsImagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuildResultsImages
            //Assert.IsInstanceOfType<BuildResultsImages> (instance, "variable 'instance' is a BuildResultsImages");
        }


        /// <summary>
        /// Test the property 'Comparison'
        /// </summary>
        [Test]
        public void ComparisonTest()
        {
            // TODO unit test for the property 'Comparison'
        }
        /// <summary>
        /// Test the property 'Diff'
        /// </summary>
        [Test]
        public void DiffTest()
        {
            // TODO unit test for the property 'Diff'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
