/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Build
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildTests
    {
        // TODO uncomment below to declare an instance variable for Build
        //private Build instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Build
            //instance = new Build();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Build
        /// </summary>
        [Test]
        public void BuildInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Build
            //Assert.IsInstanceOfType<Build> (instance, "variable 'instance' is a Build");
        }


        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Test]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }
        /// <summary>
        /// Test the property 'ComparisonID'
        /// </summary>
        [Test]
        public void ComparisonIDTest()
        {
            // TODO unit test for the property 'ComparisonID'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'DiffedAt'
        /// </summary>
        [Test]
        public void DiffedAtTest()
        {
            // TODO unit test for the property 'DiffedAt'
        }
        /// <summary>
        /// Test the property 'DiffImagesCount'
        /// </summary>
        [Test]
        public void DiffImagesCountTest()
        {
            // TODO unit test for the property 'DiffImagesCount'
        }
        /// <summary>
        /// Test the property 'DiffPercentage'
        /// </summary>
        [Test]
        public void DiffPercentageTest()
        {
            // TODO unit test for the property 'DiffPercentage'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ImagesCount'
        /// </summary>
        [Test]
        public void ImagesCountTest()
        {
            // TODO unit test for the property 'ImagesCount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProjectID'
        /// </summary>
        [Test]
        public void ProjectIDTest()
        {
            // TODO unit test for the property 'ProjectID'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

    }

}
