/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing BuildResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildResultsTests
    {
        // TODO uncomment below to declare an instance variable for BuildResults
        //private BuildResults instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuildResults
            //instance = new BuildResults();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuildResults
        /// </summary>
        [Test]
        public void BuildResultsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuildResults
            //Assert.IsInstanceOfType<BuildResults> (instance, "variable 'instance' is a BuildResults");
        }


        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Test]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'ComparisonBuild'
        /// </summary>
        [Test]
        public void ComparisonBuildTest()
        {
            // TODO unit test for the property 'ComparisonBuild'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

    }

}
