/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Images
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImagesTests
    {
        // TODO uncomment below to declare an instance variable for Images
        //private Images instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Images
            //instance = new Images();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Images
        /// </summary>
        [Test]
        public void ImagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Images
            //Assert.IsInstanceOfType<Images> (instance, "variable 'instance' is a Images");
        }


        /// <summary>
        /// Test the property '_Images'
        /// </summary>
        [Test]
        public void _ImagesTest()
        {
            // TODO unit test for the property '_Images'
        }

    }

}
