/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Image
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ImageTests
    {
        // TODO uncomment below to declare an instance variable for Image
        //private Image instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Image
            //instance = new Image();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Image
        /// </summary>
        [Test]
        public void ImageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Image
            //Assert.IsInstanceOfType<Image> (instance, "variable 'instance' is a Image");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'OriginalURL'
        /// </summary>
        [Test]
        public void OriginalURLTest()
        {
            // TODO unit test for the property 'OriginalURL'
        }
        /// <summary>
        /// Test the property 'OriginalURLWebP'
        /// </summary>
        [Test]
        public void OriginalURLWebPTest()
        {
            // TODO unit test for the property 'OriginalURLWebP'
        }
        /// <summary>
        /// Test the property 'ThumbURL'
        /// </summary>
        [Test]
        public void ThumbURLTest()
        {
            // TODO unit test for the property 'ThumbURL'
        }
        /// <summary>
        /// Test the property 'ThumbURLWebP'
        /// </summary>
        [Test]
        public void ThumbURLWebPTest()
        {
            // TODO unit test for the property 'ThumbURLWebP'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

    }

}
