/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Notifications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationsTests
    {
        // TODO uncomment below to declare an instance variable for Notifications
        //private Notifications instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Notifications
            //instance = new Notifications();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Notifications
        /// </summary>
        [Test]
        public void NotificationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Notifications
            //Assert.IsInstanceOfType<Notifications> (instance, "variable 'instance' is a Notifications");
        }


        /// <summary>
        /// Test the property 'EmailEnabled'
        /// </summary>
        [Test]
        public void EmailEnabledTest()
        {
            // TODO unit test for the property 'EmailEnabled'
        }
        /// <summary>
        /// Test the property 'SlackEnabled'
        /// </summary>
        [Test]
        public void SlackEnabledTest()
        {
            // TODO unit test for the property 'SlackEnabled'
        }
        /// <summary>
        /// Test the property 'SlackURL'
        /// </summary>
        [Test]
        public void SlackURLTest()
        {
            // TODO unit test for the property 'SlackURL'
        }

    }

}
