/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing PlanPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlanPriceTests
    {
        // TODO uncomment below to declare an instance variable for PlanPrice
        //private PlanPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlanPrice
            //instance = new PlanPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlanPrice
        /// </summary>
        [Test]
        public void PlanPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlanPrice
            //Assert.IsInstanceOfType<PlanPrice> (instance, "variable 'instance' is a PlanPrice");
        }


        /// <summary>
        /// Test the property 'USD'
        /// </summary>
        [Test]
        public void USDTest()
        {
            // TODO unit test for the property 'USD'
        }

    }

}
