/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;
using VisWiz.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing Plan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlanTests
    {
        // TODO uncomment below to declare an instance variable for Plan
        //private Plan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Plan
            //instance = new Plan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Plan
        /// </summary>
        [Test]
        public void PlanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Plan
            //Assert.IsInstanceOfType<Plan> (instance, "variable 'instance' is a Plan");
        }


        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Test]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalID'
        /// </summary>
        [Test]
        public void ExternalIDTest()
        {
            // TODO unit test for the property 'ExternalID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
