/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using VisWiz.SDK.Client;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing ImagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ImagesApiTests
    {
        private ImagesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ImagesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ImagesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ImagesApi
            //Assert.IsInstanceOfType(typeof(ImagesApi), instance, "instance is a ImagesApi");
        }

        
        /// <summary>
        /// Test CreateImage
        /// </summary>
        [Test]
        public void CreateImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string buildID = null;
            //string name = null;
            //System.IO.Stream image = null;
            //var response = instance.CreateImage(buildID, name, image);
            //Assert.IsInstanceOf<Image> (response, "response is Image");
        }
        
        /// <summary>
        /// Test GetImages
        /// </summary>
        [Test]
        public void GetImagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string buildID = null;
            //var response = instance.GetImages(buildID);
            //Assert.IsInstanceOf<Images> (response, "response is Images");
        }
        
    }

}
