/* 
 * VisWiz.io API Documentation
 *
 * This SDK allows you to query and create new projects, builds or images within the VisWiz service. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using VisWiz.SDK.Client;
using VisWiz.SDK.Client;
using VisWiz.SDK.Model;

namespace VisWiz.SDK.Test
{
    /// <summary>
    ///  Class for testing ProjectsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProjectsApiTests
    {
        private ProjectsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProjectsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProjectsApi
            //Assert.IsInstanceOfType(typeof(ProjectsApi), instance, "instance is a ProjectsApi");
        }

        
        /// <summary>
        /// Test CreateProject
        /// </summary>
        [Test]
        public void CreateProjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body1 body = null;
            //var response = instance.CreateProject(body);
            //Assert.IsInstanceOf<Project> (response, "response is Project");
        }
        
        /// <summary>
        /// Test GetProjectNotifications
        /// </summary>
        [Test]
        public void GetProjectNotificationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectID = null;
            //var response = instance.GetProjectNotifications(projectID);
            //Assert.IsInstanceOf<Notifications> (response, "response is Notifications");
        }
        
        /// <summary>
        /// Test GetProjects
        /// </summary>
        [Test]
        public void GetProjectsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProjects();
            //Assert.IsInstanceOf<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test UpdateProjectNotifications
        /// </summary>
        [Test]
        public void UpdateProjectNotificationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string projectID = null;
            //Notifications body = null;
            //var response = instance.UpdateProjectNotifications(projectID, body);
            //Assert.IsInstanceOf<Notifications> (response, "response is Notifications");
        }
        
    }

}
